import type { Metadata } from 'next';
import { Patrick_Hand, Roboto } from 'next/font/google';
import '@/app/globals.scss';
import { Providers } from '@/app/providers';
import { Header } from './Header/Header';

const patrickHand = Patrick_Hand({ subsets: ['latin'], weight: ['400'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
    title: 'Task Manager',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Providers>
            <html lang="en">
                <body className={patrickHand.className + '' + roboto.className}>
                    <Header />
                    {children}
                </body>
            </html>
        </Providers>
    );
}
