import '@/app/globals.scss';
import { Providers } from '@/app/providers';
import type { Metadata } from 'next';
import { Patrick_Hand, Roboto } from 'next/font/google';
import { Sidebar } from './Sidebar/Sidebar';
import styles from './DashBoardLayout.module.scss';

const patrickHand = Patrick_Hand({ subsets: ['latin'], weight: ['400'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
    title: 'Task Manager',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className={styles.container}>
            <Sidebar />
            {children}
        </div>
    );
}
